-- Phase 2: service requests, matching, quotes; booking link columns.
-- provider_id always references businesses.id (Phase 1 façade lock).

-- ---------------------------------------------------------------------------
-- service_requests
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_requests (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id            BIGINT NOT NULL REFERENCES users(id),
    category_id                 BIGINT REFERENCES categories(id),
    service_id                  BIGINT REFERENCES services(id),
    title                       VARCHAR(200) NOT NULL,
    description                 TEXT,
    customer_address_id         BIGINT REFERENCES customer_addresses(id),
    country_code                CHAR(2),
    region                      VARCHAR(100),
    city                        VARCHAR(100),
    area_name                   VARCHAR(150),
    latitude                    DOUBLE PRECISION,
    longitude                   DOUBLE PRECISION,
    preferred_date              DATE,
    preferred_time_from         TIME,
    preferred_time_to           TIME,
    urgency                     VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    budget_min                  NUMERIC(12,2),
    budget_max                  NUMERIC(12,2),
    currency                    CHAR(3) NOT NULL DEFAULT 'PKR',
    status                      VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    selected_provider_id        BIGINT REFERENCES businesses(id),
    selected_quote_id           BIGINT,
    booking_id                  BIGINT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at                  TIMESTAMPTZ,
    deleted_at                  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_service_requests_customer
    ON service_requests (customer_user_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_service_requests_status
    ON service_requests (status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_service_requests_category
    ON service_requests (category_id) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- service_request_media
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_request_media (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      BIGINT NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    media_asset_id  BIGINT REFERENCES media_assets(id),
    storage_key     VARCHAR(512),
    url             VARCHAR(1024),
    mime_type       VARCHAR(128),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_service_request_media_request
    ON service_request_media (request_id);

-- ---------------------------------------------------------------------------
-- service_request_providers (matching / inbox)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_request_providers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id       BIGINT NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    provider_id      BIGINT NOT NULL REFERENCES businesses(id),
    match_score      NUMERIC(8,2) NOT NULL DEFAULT 0,
    response_status  VARCHAR(32) NOT NULL DEFAULT 'INVITED',
    responded_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (request_id, provider_id)
);

CREATE INDEX IF NOT EXISTS idx_srp_provider_status
    ON service_request_providers (provider_id, response_status);

-- ---------------------------------------------------------------------------
-- quotes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quotes (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id                  BIGINT NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    provider_id                 BIGINT NOT NULL REFERENCES businesses(id),
    amount                      NUMERIC(12,2) NOT NULL,
    currency                    CHAR(3) NOT NULL DEFAULT 'PKR',
    description                 TEXT,
    estimated_duration_minutes  INT,
    valid_until                 TIMESTAMPTZ,
    status                      VARCHAR(32) NOT NULL DEFAULT 'SENT',
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at                  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_quotes_request ON quotes (request_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_quotes_provider ON quotes (provider_id) WHERE deleted_at IS NULL;

ALTER TABLE service_requests
    DROP CONSTRAINT IF EXISTS fk_service_requests_selected_quote;
ALTER TABLE service_requests
    ADD CONSTRAINT fk_service_requests_selected_quote
    FOREIGN KEY (selected_quote_id) REFERENCES quotes(id);

-- ---------------------------------------------------------------------------
-- bookings: request/quote links + source normalize
-- ---------------------------------------------------------------------------
ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS service_request_id BIGINT REFERENCES service_requests(id),
    ADD COLUMN IF NOT EXISTS quote_id BIGINT REFERENCES quotes(id);

UPDATE bookings SET source = 'DIRECT'
WHERE source IS NULL OR source = '' OR UPPER(source) IN ('MARKETPLACE', 'DIRECT_APPOINTMENT');

ALTER TABLE bookings ALTER COLUMN source SET DEFAULT 'DIRECT';

CREATE INDEX IF NOT EXISTS idx_bookings_service_request
    ON bookings (service_request_id) WHERE service_request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bookings_quote
    ON bookings (quote_id) WHERE quote_id IS NOT NULL;

ALTER TABLE service_requests
    DROP CONSTRAINT IF EXISTS fk_service_requests_booking;
ALTER TABLE service_requests
    ADD CONSTRAINT fk_service_requests_booking
    FOREIGN KEY (booking_id) REFERENCES bookings(id);

-- ---------------------------------------------------------------------------
-- Feature flags
-- ---------------------------------------------------------------------------
INSERT INTO feature_flags (code, description, is_enabled_global, rules)
VALUES
    ('service_requests', 'Allow customers to create marketplace service requests', TRUE, NULL),
    ('jobs', 'Enable job lifecycle for request-sourced bookings', TRUE, NULL),
    ('community', 'Enable local community module', TRUE, NULL)
ON CONFLICT (code) DO NOTHING;
