-- Phase 3: job lifecycle for request-sourced bookings.
-- provider_id always references businesses.id (Phase 1 façade lock).

CREATE TABLE IF NOT EXISTS jobs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT REFERENCES bookings(id),
    service_request_id  BIGINT REFERENCES service_requests(id),
    provider_id         BIGINT NOT NULL REFERENCES businesses(id),
    customer_id         BIGINT NOT NULL REFERENCES users(id),
    service_id          BIGINT REFERENCES services(id),
    title               VARCHAR(200) NOT NULL,
    description         TEXT,
    estimated_amount    NUMERIC(12,2),
    final_amount        NUMERIC(12,2),
    currency            CHAR(3) NOT NULL DEFAULT 'PKR',
    status              VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    scheduled_start     TIMESTAMPTZ,
    scheduled_end       TIMESTAMPTZ,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_jobs_provider_status ON jobs (provider_id, status);
CREATE INDEX IF NOT EXISTS idx_jobs_customer ON jobs (customer_id);
CREATE INDEX IF NOT EXISTS idx_jobs_booking ON jobs (booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_jobs_scheduled_start ON jobs (scheduled_start) WHERE scheduled_start IS NOT NULL;

CREATE TABLE IF NOT EXISTS job_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    from_status     VARCHAR(32),
    to_status       VARCHAR(32) NOT NULL,
    changed_by      BIGINT REFERENCES users(id),
    reason          TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_status_history_job ON job_status_history (job_id, created_at);

CREATE TABLE IF NOT EXISTS job_media (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    media_asset_id  BIGINT REFERENCES media_assets(id),
    url             VARCHAR(1024),
    storage_key     VARCHAR(512),
    mime_type       VARCHAR(128),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_media_job ON job_media (job_id);

CREATE TABLE IF NOT EXISTS job_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    author_user_id  BIGINT NOT NULL REFERENCES users(id),
    body            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_notes_job ON job_notes (job_id, created_at);

CREATE TABLE IF NOT EXISTS disputes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    opened_by_user_id   BIGINT NOT NULL REFERENCES users(id),
    reason              TEXT NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    resolution_notes    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_disputes_job ON disputes (job_id);
CREATE INDEX IF NOT EXISTS idx_disputes_status ON disputes (status);
