-- Phase 6: local service communities (lean schema).

CREATE TABLE IF NOT EXISTS communities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    slug            VARCHAR(150) NOT NULL UNIQUE,
    description     TEXT,
    country_code    CHAR(2),
    region          VARCHAR(100),
    city            VARCHAR(100),
    area_name       VARCHAR(150),
    status          VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_communities_city ON communities (city, status);

CREATE TABLE IF NOT EXISTS community_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id    BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role            VARCHAR(32) NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (community_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_community_members_user ON community_members (user_id);

CREATE TABLE IF NOT EXISTS community_posts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id            BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    author_user_id          BIGINT NOT NULL REFERENCES users(id),
    provider_business_id    BIGINT REFERENCES businesses(id),
    category                VARCHAR(64) NOT NULL DEFAULT 'GENERAL',
    title                   VARCHAR(200) NOT NULL,
    body                    TEXT NOT NULL,
    status                  VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_community_posts_community
    ON community_posts (community_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS community_comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
    author_user_id  BIGINT NOT NULL REFERENCES users(id),
    body            TEXT NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_community_comments_post
    ON community_comments (post_id, created_at) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS community_reactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reaction_type   VARCHAR(32) NOT NULL DEFAULT 'LIKE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (post_id, user_id, reaction_type)
);

CREATE INDEX IF NOT EXISTS idx_community_reactions_post ON community_reactions (post_id);

CREATE TABLE IF NOT EXISTS community_reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT REFERENCES community_posts(id) ON DELETE CASCADE,
    comment_id          BIGINT REFERENCES community_comments(id) ON DELETE CASCADE,
    reported_by_user_id BIGINT NOT NULL REFERENCES users(id),
    reason              VARCHAR(64) NOT NULL,
    description         TEXT,
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reviewed_by_user_id BIGINT REFERENCES users(id),
    reviewed_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (post_id IS NOT NULL OR comment_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_community_reports_status ON community_reports (status);

-- Seed a default community for demos
INSERT INTO communities (name, slug, description, country_code, city, area_name, status)
VALUES ('Karachi Home Services', 'karachi-home-services',
        'Local recommendations and questions for home services in Karachi',
        'PK', 'Karachi', 'Clifton', 'ACTIVE')
ON CONFLICT (slug) DO NOTHING;
