-- Phase 7: monthly usage counters per organization.

CREATE TABLE IF NOT EXISTS organization_usage_counters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    period_ym       CHAR(7) NOT NULL,
    metric_code     VARCHAR(64) NOT NULL,
    count           BIGINT NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (organization_id, period_ym, metric_code)
);

CREATE INDEX IF NOT EXISTS idx_org_usage_org_period
    ON organization_usage_counters (organization_id, period_ym);
