-- Dynamic weekly availability: multiple open intervals per day + persisted slot step.

ALTER TABLE branch_working_hours
    ADD COLUMN IF NOT EXISTS slot_step_minutes INT NOT NULL DEFAULT 30;

ALTER TABLE staff_working_hours
    ADD COLUMN IF NOT EXISTS slot_step_minutes INT NOT NULL DEFAULT 30;

CREATE TABLE IF NOT EXISTS branch_working_intervals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    working_hour_id   BIGINT NOT NULL REFERENCES branch_working_hours(id) ON DELETE CASCADE,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL,
    sort_order        INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS staff_working_intervals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    working_hour_id   BIGINT NOT NULL REFERENCES staff_working_hours(id) ON DELETE CASCADE,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL,
    sort_order        INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_branch_working_intervals_hour
    ON branch_working_intervals (working_hour_id);

CREATE INDEX IF NOT EXISTS idx_staff_working_intervals_hour
    ON staff_working_intervals (working_hour_id);

-- Backfill one interval from existing open day windows.
INSERT INTO branch_working_intervals (working_hour_id, start_time, end_time, sort_order)
SELECT id, start_time, end_time, 0
FROM branch_working_hours
WHERE closed = FALSE
  AND start_time IS NOT NULL
  AND end_time IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM branch_working_intervals i WHERE i.working_hour_id = branch_working_hours.id
  );

INSERT INTO staff_working_intervals (working_hour_id, start_time, end_time, sort_order)
SELECT id, start_time, end_time, 0
FROM staff_working_hours
WHERE closed = FALSE
  AND start_time IS NOT NULL
  AND end_time IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM staff_working_intervals i WHERE i.working_hour_id = staff_working_hours.id
  );
