-- Phase 1 provider listing foundation.
-- Provider = businesses façade; individuals get implicit org/business/branch/staff.

-- ---------------------------------------------------------------------------
-- Organizations
-- ---------------------------------------------------------------------------
ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS listing_mode VARCHAR(32) NOT NULL DEFAULT 'BUSINESS';

UPDATE organizations SET listing_mode = 'BUSINESS' WHERE listing_mode IS NULL OR listing_mode = '';

-- ---------------------------------------------------------------------------
-- Businesses (public listing façade)
-- ---------------------------------------------------------------------------
ALTER TABLE businesses
    ADD COLUMN IF NOT EXISTS listing_mode VARCHAR(32) NOT NULL DEFAULT 'BUSINESS',
    ADD COLUMN IF NOT EXISTS provider_type VARCHAR(32) NOT NULL DEFAULT 'BUSINESS',
    ADD COLUMN IF NOT EXISTS service_mode VARCHAR(32) NOT NULL DEFAULT 'AT_PROVIDER',
    ADD COLUMN IF NOT EXISTS publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS onboarding_state VARCHAR(32) NOT NULL DEFAULT 'STARTED',
    ADD COLUMN IF NOT EXISTS years_experience INT,
    ADD COLUMN IF NOT EXISTS travel_buffer_minutes INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(64);

UPDATE businesses
SET listing_mode = COALESCE(NULLIF(listing_mode, ''), 'BUSINESS'),
    provider_type = COALESCE(NULLIF(provider_type, ''), 'BUSINESS'),
    service_mode = COALESCE(NULLIF(service_mode, ''), 'AT_PROVIDER'),
    travel_buffer_minutes = COALESCE(travel_buffer_minutes, 0);

UPDATE businesses
SET publish_status = CASE
        WHEN status = 'APPROVED' THEN 'PUBLISHED'
        ELSE 'DRAFT'
    END
WHERE publish_status IS NULL OR publish_status = '' OR publish_status = 'DRAFT';

-- Re-apply carefully: only backfill rows that still look like defaults from ADD COLUMN
UPDATE businesses
SET publish_status = 'PUBLISHED'
WHERE status = 'APPROVED' AND publish_status = 'DRAFT';

UPDATE businesses
SET onboarding_state = CASE
        WHEN status = 'APPROVED' THEN 'PUBLISHED'
        ELSE COALESCE(NULLIF(onboarding_state, ''), 'STARTED')
    END;

UPDATE businesses
SET provider_type = 'INDIVIDUAL'
WHERE listing_mode = 'INDIVIDUAL' AND provider_type <> 'INDIVIDUAL';

-- ---------------------------------------------------------------------------
-- Branches / staff implicit flags
-- ---------------------------------------------------------------------------
ALTER TABLE branches
    ADD COLUMN IF NOT EXISTS is_implicit BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE staff
    ADD COLUMN IF NOT EXISTS is_implicit BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE branches SET is_implicit = FALSE WHERE is_implicit IS NULL;
UPDATE staff SET is_implicit = FALSE WHERE is_implicit IS NULL;

-- ---------------------------------------------------------------------------
-- Services pricing / mode extensions
-- ---------------------------------------------------------------------------
ALTER TABLE services
    ADD COLUMN IF NOT EXISTS service_mode VARCHAR(32) NOT NULL DEFAULT 'AT_PROVIDER',
    ADD COLUMN IF NOT EXISTS pricing_type VARCHAR(32) NOT NULL DEFAULT 'FIXED',
    ADD COLUMN IF NOT EXISTS duration_type VARCHAR(32) NOT NULL DEFAULT 'FIXED',
    ADD COLUMN IF NOT EXISTS requires_quote BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS allows_home_service BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS minimum_price NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS maximum_price NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS estimated_duration_minutes INT;

UPDATE services
SET service_mode = COALESCE(NULLIF(service_mode, ''), 'AT_PROVIDER'),
    pricing_type = COALESCE(NULLIF(pricing_type, ''), 'FIXED'),
    duration_type = COALESCE(NULLIF(duration_type, ''), 'FIXED'),
    requires_quote = COALESCE(requires_quote, FALSE),
    allows_home_service = COALESCE(allows_home_service, FALSE);

-- ---------------------------------------------------------------------------
-- Named geographic areas (admin-managed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS geo_areas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code  VARCHAR(8) NOT NULL,
    region        VARCHAR(128),
    city          VARCHAR(128) NOT NULL,
    name          VARCHAR(128) NOT NULL,
    slug          VARCHAR(160) NOT NULL,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    status        VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,
    deleted_at    TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_geo_areas_country_city_slug_live
    ON geo_areas (country_code, city, slug)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_geo_areas_city
    ON geo_areas (country_code, city)
    WHERE deleted_at IS NULL AND status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- Business service coverage
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS business_service_areas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id    BIGINT NOT NULL REFERENCES businesses(id),
    coverage_type  VARCHAR(32) NOT NULL,
    geo_area_id    BIGINT REFERENCES geo_areas(id),
    area_name      VARCHAR(128),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    radius_km      NUMERIC(8,2),
    status         VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT chk_bsa_coverage_type CHECK (coverage_type IN ('NAMED', 'RADIUS')),
    CONSTRAINT chk_bsa_named CHECK (
        coverage_type <> 'NAMED' OR geo_area_id IS NOT NULL
    ),
    CONSTRAINT chk_bsa_radius CHECK (
        coverage_type <> 'RADIUS'
        OR (latitude IS NOT NULL AND longitude IS NOT NULL AND radius_km IS NOT NULL AND radius_km > 0 AND radius_km <= 50)
    )
);

CREATE INDEX IF NOT EXISTS idx_business_service_areas_business
    ON business_service_areas (business_id)
    WHERE deleted_at IS NULL AND status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- Customer saved addresses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_addresses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id   BIGINT NOT NULL REFERENCES users(id),
    label              VARCHAR(64) NOT NULL,
    address_line       VARCHAR(512) NOT NULL,
    country_code       VARCHAR(8) NOT NULL,
    region             VARCHAR(128),
    city               VARCHAR(128),
    area_name          VARCHAR(128),
    postal_code        VARCHAR(32),
    geo_area_id        BIGINT REFERENCES geo_areas(id),
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    is_default         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ,
    deleted_at         TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_addresses_default_live
    ON customer_addresses (customer_user_id)
    WHERE is_default = TRUE AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_customer_addresses_user
    ON customer_addresses (customer_user_id)
    WHERE deleted_at IS NULL;

-- One-time copy from customer_profiles when present
INSERT INTO customer_addresses (
    customer_user_id, label, address_line, country_code, region, city, postal_code, is_default, created_at
)
SELECT
    cp.user_id,
    'Home',
    cp.address_line1,
    COALESCE(NULLIF(cp.country_code, ''), 'PK'),
    cp.region,
    cp.city,
    cp.postal_code,
    TRUE,
    COALESCE(cp.created_at, NOW())
FROM customer_profiles cp
WHERE cp.deleted_at IS NULL
  AND cp.address_line1 IS NOT NULL
  AND TRIM(cp.address_line1) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM customer_addresses ca
      WHERE ca.customer_user_id = cp.user_id AND ca.deleted_at IS NULL
  );

-- ---------------------------------------------------------------------------
-- Discovery indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_businesses_slug_live
    ON businesses (slug)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_businesses_listing_discover
    ON businesses (status, publish_status, listing_mode, service_mode)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Feature flag + plan entitlements
-- ---------------------------------------------------------------------------
INSERT INTO feature_flags (code, description, is_enabled_global, rules)
VALUES (
    'individual_providers',
    'Allow individual professional registration and public listing',
    TRUE,
    NULL
)
ON CONFLICT (code) DO NOTHING;

INSERT INTO plan_entitlements (plan_id, entitlement_code, value_type, value)
SELECT p.id, e.entitlement_code, e.value_type, e.value
FROM subscription_plans p
JOIN (VALUES
    ('STARTER',  'home_service',      'BOOL', 'true'),
    ('STARTER',  'max_service_areas', 'INT',  '3'),
    ('STUDIO',   'home_service',      'BOOL', 'true'),
    ('STUDIO',   'max_service_areas', 'INT',  '8'),
    ('BUSINESS', 'home_service',      'BOOL', 'true'),
    ('BUSINESS', 'max_service_areas', 'INT',  '20'),
    ('CHAIN',    'home_service',      'BOOL', 'true'),
    ('CHAIN',    'max_service_areas', 'INT',  '999')
) AS e(plan_code, entitlement_code, value_type, value) ON e.plan_code = p.code
ON CONFLICT (plan_id, entitlement_code) DO NOTHING;

-- Demo-named Lahore areas (clearly product demo, not official boundaries)
INSERT INTO geo_areas (country_code, region, city, name, slug, latitude, longitude, status, created_at)
SELECT v.country_code, v.region, v.city, v.name, v.slug, v.latitude, v.longitude, 'ACTIVE', NOW()
FROM (VALUES
    ('PK', 'Punjab', 'Lahore', 'Demo DHA Phase 5', 'demo-dha-phase-5', 31.4697, 74.4105),
    ('PK', 'Punjab', 'Lahore', 'Demo Gulberg', 'demo-gulberg', 31.5102, 74.3441),
    ('PK', 'Punjab', 'Lahore', 'Demo Model Town', 'demo-model-town', 31.4824, 74.3250),
    ('PK', 'Punjab', 'Lahore', 'Demo Johar Town', 'demo-johar-town', 31.4697, 74.2728)
) AS v(country_code, region, city, name, slug, latitude, longitude)
WHERE NOT EXISTS (
    SELECT 1 FROM geo_areas g
    WHERE g.country_code = v.country_code AND g.city = v.city AND g.slug = v.slug AND g.deleted_at IS NULL
);
